### ISSUE TITLE
How to get the right values..

### ISSUE THREAD

**Issue by osmanburucu-ibm** [arnoldst/ucd-install-on-roks#1]
I was wondering how to get the version identifier for the server and the agent? Where can i look it up which versions are available?
image:
  repository: cp.icr.io/ibm-ucds
  tag: "7.1.0.2.1063225"
  pullPolicy: Always
  secret: ""

**Comment by arnoldst** [comment]
You can do this to get the default value of the helm chart - helm inspect values entitled/ibm-ucd-prod > myvalues.yaml
However, I've not found an easy way of finding all the possible tags - as you can't do it via the docker command line.  The only way I found was to pull all the images - but not something I'd recommend.

**Comment by osmanburucu** [comment]
OK. Thank you. I found the information about the latest version
with  helm inspect values ibm-helm/ibm-ucd-prod then scroll for version
